version: "2"

run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - errorlint
    - gocritic
    - gosec
    - misspell
    - revive
    - unconvert
    - unparam
  settings:
    govet:
      enable-all: true
    revive:
      rules:
        - name: exported
          severity: warning
        - name: file-length-limit
          arguments:
            - maxLines: 300
          severity: error

exclusions:
  rules:
    - path: _test\.go
      linters:
        - gosec
    - path: ".*\\.pb\\.go"
      linters:
        - revive
    - path: ".*_gen\\.go"
      linters:
        - revive
